---
# https://docs.nvidia.com/datacenter/tesla/index.html
nvidia_driver_version: '580.105.08'
nvidia_driver_executable: 'NVIDIA-Linux-x86_64-{{ nvidia_driver_version }}.run'
nvidia_driver_url: 'https://us.download.nvidia.com/tesla/{{ nvidia_driver_version }}/{{ nvidia_driver_executable }}'

nvidia_fabric_manager_archive: 'fabricmanager-linux-x86_64-{{ nvidia_driver_version }}-archive.tar.xz'
nvidia_fabric_manager_url: 'https://developer.download.nvidia.com/compute/nvidia-driver/redist/fabricmanager/linux-x86_64/{{ nvidia_fabric_manager_archive }}'

# https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-verify.html
efa_installer_version: '1.46.0'
efa_installer_archive: 'aws-efa-installer-{{ efa_installer_version }}.tar.gz'
efa_installer_url: 'https://efa-installer.amazonaws.com/{{ efa_installer_archive }}'
efa_installer_checksum: 'sha256:8302bd7849afb95c903a875d7dcb6f85b3d7629e9a8b67d020031cfc6f4d0ee1'

# https://github.com/aws/aws-ofi-nccl/releases
aws_ofi_nccl_version: '1.17.3'
